name: py27

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Install ROOT
      run: |
        curl -O https://root.cern.ch/download/root_v6.12.06.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
        tar xzf root_v6.12.06.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
        source root/bin/thisroot.sh
    - name: Install hepdata_lip
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install --upgrade enum34 pytest_pylint configparser astroid coveralls
    - name: Test with pytest
      run: |
        source root/bin/thisroot.sh
        python setup.py test
